alias: Musicbox Spotify Start Playback
description: ""
triggers: []
conditions: []
actions:
  - target:
      entity_id: media_player.spotify_tobias_munzert
    data:
      source: sk61
    action: media_player.select_source
  - repeat:
      while:
        - condition: not
          conditions:
            - condition: state
              entity_id: media_player.spotify_tobias_munzert
              state: sk61
              for:
                hours: 0
                minutes: 0
                seconds: 0
              attribute: source
      sequence:
        - delay:
            hours: 0
            minutes: 0
            seconds: 1
            milliseconds: 0
        - data:
            message: >
              Waiting for Spotify to play. Current state: {{
              states('media_player.spotify_tobias_munzert') }}
            level: warning
          action: system_log.write
  - action: media_player.repeat_set
    metadata: {}
    data:
      repeat: one
    target:
      entity_id: media_player.spotify_tobias_munzert
  - target:
      entity_id: media_player.spotify_tobias_munzert
    data:
      media_content_type: "{{ content_type }}"
      media_content_id: "{{ content }}"
    action: media_player.play_media
mode: single
